[package]
name = "unsafe_alternatives"
description = "The alternative unsafe syntax for Rust."
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
unsafe_alternatives_builder = { path = "unsafe_alternatives_builder" }
